import turtle
screen = turtle.Screen()
screen.title('Celebrating 5 years of Naman Uriti Channel')
pencil = turtle.Turtle()
pencil.shape('turtle')
pencil.width(7)
pencil.penup()
pencil.backward(275)
pencil.left(90)
pencil.forward(150)
pencil.right(90)
pencil.forward(100)
pencil.pendown()
pencil.backward(100)
pencil.right(90)
pencil.forward(75)
pencil.left(125)
for i in range(1,239):
    pencil.right(1)
    pencil.forward(1)
pencil.penup()
pencil.right(157)
pencil.forward(123)
pencil.write("Years Of", font=("times new roman", 100))
pencil.right(155)
pencil.forward(140)
pencil.write("NAMAN URITI CHANNEL", font=("times new roman", 48))
pencil.left(155)
pencil.forward(105)
pencil.pendown()
pencil.width(1)
pencil.fillcolor("#FF0000")
pencil.begin_fill()
pencil.forward(135)
for i in range(1,91):
    pencil.right(1)
    pencil.forward(0.75)
pencil.forward(50)
for i in range(1,91):
    pencil.right(1)
    pencil.forward(0.75)
pencil.forward(135)
for i in range(1,91):
    pencil.right(1)
    pencil.forward(0.75)
pencil.forward(50)
for i in range(1,91):
    pencil.right(1)
    pencil.forward(0.75)
pencil.end_fill()
pencil.penup()
pencil.forward(50)
pencil.right(90)
pencil.forward(135/2)
pencil.right(180)
pencil.forward(55/2)
pencil.right(180)
pencil.pendown()
pencil.fillcolor("#FFFFFF")
pencil.begin_fill()
pencil.forward(55)
pencil.left(120)
pencil.forward(55)
pencil.left(120)
pencil.forward(55)
pencil.left(120)
pencil.end_fill()
pencil.hideturtle()
screen.mainloop()
